/**
 * Generates the three figures for the write-up as Astro components holding
 * inline SVG. Run it whenever the numbers change:
 *
 *   pnpm --filter @rdm/jev-mock figures
 *
 * Inline rather than .svg files so the marks inherit the site's palette
 * variables and the type scales with the page.
 *
 * Palette: amber / blue / rose, validated against the --bg-card surface for
 * colorblind separation (worst all-pairs CVD delta-E 13.2, normal-vision 19.3).
 * Identity is fixed across every figure: amber is the honest model, rose is the
 * overconfident one, blue is the underconfident one.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { calibratedJev } from './mock.ts';
import { evaluate, threshold, type Costs } from './policy.ts';
import { reliabilityTable } from './eval.ts';
import type { Pair } from './calibration.ts';

const OUT = resolve(import.meta.dirname, '../../../apps/site/src/components/faking-calibration');

const HONEST = '#c98500';
const HOT = '#d55181';
const COLD = '#3987e5';

const W = 660;
const H = 380;
const M = { top: 34, right: 96, bottom: 46, left: 66 };
const PW = W - M.left - M.right;
const PH = H - M.top - M.bottom;

const sx = (v: number) => M.left + v * PW;
const sy = (v: number) => M.top + (1 - v) * PH;
const n2 = (v: number) => Math.round(v * 100) / 100;

function frame(opts: {
  xLabel: string;
  yLabel: string;
  ticks?: number[];
  yTicks?: boolean;
}): string {
  const ticks = opts.ticks ?? [0, 0.25, 0.5, 0.75, 1];
  const grid = ticks
    .map(
      (t) =>
        `<line x1="${n2(sx(t))}" y1="${M.top}" x2="${n2(sx(t))}" y2="${M.top + PH}" class="grid" />` +
        `<line x1="${M.left}" y1="${n2(sy(t))}" x2="${M.left + PW}" y2="${n2(sy(t))}" class="grid" />`,
    )
    .join('');
  const xt = ticks
    .map((t) => `<text x="${n2(sx(t))}" y="${M.top + PH + 20}" class="tick mid">${t}</text>`)
    .join('');
  const yt =
    opts.yTicks === false
      ? ''
      : ticks
          .map((t) => `<text x="${M.left - 10}" y="${n2(sy(t)) + 4}" class="tick end">${t}</text>`)
          .join('');
  return `${grid}
    <line x1="${M.left}" y1="${M.top + PH}" x2="${M.left + PW}" y2="${M.top + PH}" class="axis" />
    <line x1="${M.left}" y1="${M.top}" x2="${M.left}" y2="${M.top + PH}" class="axis" />
    ${xt}${yt}
    <text x="${n2(M.left + PW / 2)}" y="${H - 8}" class="label mid">${opts.xLabel}</text>
    <text x="12" y="${n2(M.top + PH / 2)}" class="label mid" transform="rotate(-90 12 ${n2(M.top + PH / 2)})">${opts.yLabel}</text>`;
}

/** Fixed-position legend rows in the right margin. Anchoring a label to a
 *  curve's endpoint is how legends collide; two curves that converge produce
 *  two labels in the same place. */
function legend(rows: { label: string; color: string; note?: string; dashed?: boolean }[]): string {
  const x = M.left + PW + 12;
  return rows
    .map((row, i) => {
      const y = M.top + 12 + i * 34;
      return (
        `<line x1="${x}" y1="${y - 4}" x2="${x + 14}" y2="${y - 4}" stroke="${row.color}" stroke-width="2.5" stroke-linecap="round"${row.dashed ? ' stroke-dasharray="4 3"' : ''} />` +
        `<text x="${x}" y="${y + 14}" class="key" fill="${row.color}">${row.label}</text>` +
        (row.note ? `<text x="${x}" y="${y + 28}" class="note">${row.note}</text>` : '')
      );
    })
    .join('');
}

const path = (pts: [number, number][]) =>
  pts.map(([x, y], i) => `${i === 0 ? 'M' : 'L'}${n2(sx(x))} ${n2(sy(y))}`).join(' ');

const STYLE = `
  .fig { width: 100%; height: auto; display: block; margin: 2.4rem auto 0.6rem; }
  .fig text { font-family: var(--font-jetbrains); fill: var(--text-dim); }
  .fig .tick { font-size: 11px; }
  .fig .label { font-size: 11.5px; fill: var(--text-muted); }
  .fig .mid { text-anchor: middle; }
  .fig .end { text-anchor: end; }
  .fig .grid { stroke: var(--border); stroke-width: 1; }
  .fig .axis { stroke: var(--border); stroke-width: 1.5; }
  .fig .ref { stroke: var(--text-muted); stroke-width: 1.5; stroke-dasharray: 4 4; fill: none; }
  .fig .series { fill: none; stroke-width: 2; stroke-linecap: round; }
  .fig .key { font-size: 11.5px; fill: var(--text); }
  .fig .note { font-size: 11px; fill: var(--text-muted); }
  .fig figcaption, figcaption {
    font-family: var(--font-jetbrains);
    font-size: 0.72rem;
    line-height: 1.5;
    color: var(--text-muted);
    max-width: 34rem;
    margin: 0 auto 2.6rem;
    text-align: center;
  }
`;

function component(inner: string, caption: string): string {
  return `---
// Generated by packages/jev-mock/src/figures.ts. Do not edit by hand.
---

<figure>
${inner}
  <figcaption>${caption}</figcaption>
</figure>

<style>${STYLE}</style>
`;
}

// --- figure 1: the temperature knob ----------------------------------------

const logit = (p: number) => Math.log(p / (1 - p));
const sigmoid = (x: number) => 1 / (1 + Math.exp(-x));
const temper = (p: number, t: number) => sigmoid(logit(Math.min(0.9995, Math.max(0.0005, p))) / t);

function figureTemperature(): string {
  const xs = Array.from({ length: 121 }, (_, i) => i / 120);
  const curve = (t: number) => xs.map((x) => [x, temper(x, t)] as [number, number]);

  const inner = `  <svg class="fig" viewBox="0 0 ${W} ${H}" role="img"
    aria-label="Reported probability against honest probability. Temperature below one bends the curve away from the diagonal toward the corners; above one flattens it toward the middle.">
    ${frame({ xLabel: 'what the model actually believes', yLabel: 'what it reports' })}
    <path d="${path(xs.map((x) => [x, x] as [number, number]))}" fill="none" stroke="${HONEST}" stroke-width="2" stroke-dasharray="5 4" />
    <path class="series" d="${path(curve(0.5))}" stroke="${HOT}"><title>temperature 0.5, overconfident</title></path>
    <path class="series" d="${path(curve(2.5))}" stroke="${COLD}"><title>temperature 2.5, underconfident</title></path>
    <circle cx="${n2(sx(0.8))}" cy="${n2(sy(temper(0.8, 0.5)))}" r="4.5" fill="${HOT}" stroke="var(--bg)" stroke-width="2"><title>believes 0.80, reports 0.92</title></circle>
    <circle cx="${n2(sx(0.8))}" cy="${n2(sy(0.8))}" r="4.5" fill="${HONEST}" stroke="var(--bg)" stroke-width="2"><title>believes 0.80, reports 0.80</title></circle>
    <circle cx="${n2(sx(0.8))}" cy="${n2(sy(temper(0.8, 2.5)))}" r="4.5" fill="${COLD}" stroke="var(--bg)" stroke-width="2"><title>believes 0.80, reports 0.62</title></circle>
    ${legend([
      { label: 'T = 0.5', color: HOT, note: 'says 0.92' },
      { label: 'T = 1', color: HONEST, note: 'says 0.80', dashed: true },
      { label: 'T = 2.5', color: COLD, note: 'says 0.62' },
    ])}
    <line x1="${n2(sx(0.8))}" y1="${M.top}" x2="${n2(sx(0.8))}" y2="${M.top + PH}" class="ref" opacity="0.45" />
  </svg>`;

  return component(
    inner,
    'One knob. Below 1 the curve bends toward the corners &mdash; every belief gets pushed nearer 0 or 1, so the model sounds surer than it is. Above 1 it sags toward the middle and the model hedges everything. Three models that genuinely believe 0.8 report 0.92, 0.80 and 0.62. All three rank the same items in the same order.',
  );
}

// --- figure 2: reliability diagram -----------------------------------------

async function stream(temperature: number, n: number): Promise<Pair[]> {
  const mock = calibratedJev({ seed: 42, temperature });
  const q = { urgent: { type: 'boolean' as const, instructions: 'Does this convey urgency?' } };
  for (let i = 0; i < n; i++) await mock.decide(`ticket ${i}`, q);
  return mock.log.map((o) => o.pair);
}

async function figureReliability(): Promise<string> {
  const series = [
    { label: 'honest', color: HONEST, pairs: await stream(1, 20000) },
    { label: 'T = 0.5', color: HOT, pairs: await stream(0.5, 20000) },
  ];

  const drawn = series
    .map(({ label, color, pairs }) => {
      const table = reliabilityTable(pairs).filter((b) => b.count > 0);
      const bars = table
        .map(
          (b) =>
            `<line x1="${n2(sx(b.meanP))}" y1="${n2(sy(b.interval.lo))}" x2="${n2(sx(b.meanP))}" y2="${n2(sy(b.interval.hi))}" stroke="${color}" stroke-width="1.5" opacity="0.55" />`,
        )
        .join('');
      const dots = table
        .map(
          (b) =>
            `<circle cx="${n2(sx(b.meanP))}" cy="${n2(sy(b.meanY))}" r="4.5" fill="${color}" stroke="var(--bg)" stroke-width="2">` +
            `<title>${label}: claimed ${b.meanP.toFixed(2)}, happened ${b.meanY.toFixed(2)} (n=${b.count})</title></circle>`,
        )
        .join('');
      const line = `<path class="series" d="${path(table.map((b) => [b.meanP, b.meanY] as [number, number]))}" stroke="${color}" opacity="0.8" />`;
      return line + bars + dots;
    })
    .join('\n    ');

  const inner = `  <svg class="fig" viewBox="0 0 ${W} ${H}" role="img"
    aria-label="Observed frequency against claimed probability, ten bins, with 95 percent intervals. The honest model tracks the diagonal. The overconfident model crosses it, running high at the bottom and low at the top.">
    ${frame({ xLabel: 'probability the model claimed', yLabel: 'how often it happened' })}
    <path class="ref" d="${path([[0, 0], [1, 1]])}" />
    <text x="${n2(sx(0.52))}" y="${n2(sy(0.14))}" class="note">the dashed line is perfect honesty</text>
    ${drawn}
    ${legend([
      { label: 'honest', color: HONEST, note: 'on the line' },
      { label: 'T = 0.5', color: HOT, note: 'crosses it' },
    ])}
  </svg>`;

  return component(
    inner,
    'Twenty thousand yes/no calls, bucketed by the probability the model reported. Vertical bars are 95% intervals &mdash; without them this chart is a Rorschach test. Amber sits on the diagonal. Rose crosses it: in the 0.1 bucket things happen 31% of the time, and in the 0.85 bucket only 73%. It is wrong in both directions at once, which is what sounding confident looks like from the outside.',
  );
}

// --- figure 3: the cost bowl -----------------------------------------------

async function figureCost(): Promise<string> {
  const costs: Costs = { falsePositive: 5, falseNegative: 20 };
  const pairs = await stream(1, 20000);
  const cost = (t: number) =>
    evaluate(pairs, costs, { lo: t, hi: t, degenerate: true }).costPerItem;

  // Clipped at $3: past the right wall the curve runs to $10 and squashes the
  // part anyone is deciding between.
  const yTop = 3;
  const steps = 300;
  const pts: [number, number][] = [];
  for (let i = 0; i <= steps; i++) {
    const t = i / steps;
    pts.push([t, Math.min(cost(t) / yTop, 1.04)]);
  }

  const derived = threshold(costs);
  const atDerived = cost(derived);
  const atHalf = cost(0.5);

  const yLabels = [0, 0.5, 1, 1.5, 2, 2.5, 3]
    .map(
      (v) =>
        `<text x="${M.left - 10}" y="${n2(sy(v / yTop)) + 4}" class="tick end">$${v.toFixed(2)}</text>` +
        `<line x1="${M.left}" y1="${n2(sy(v / yTop))}" x2="${M.left + PW}" y2="${n2(sy(v / yTop))}" class="grid" />`,
    )
    .join('');

  const mark = (t: number, c: number, color: string, label: string, above: boolean) => {
    const y = sy(c / yTop);
    const ty = above ? y - 30 : y + 26;
    return (
      `<line x1="${n2(sx(t))}" y1="${n2(y)}" x2="${n2(sx(t))}" y2="${M.top + PH}" stroke="${color}" stroke-width="1.5" stroke-dasharray="3 3" opacity="0.7" />` +
      `<circle cx="${n2(sx(t))}" cy="${n2(y)}" r="5" fill="${color}" stroke="var(--bg)" stroke-width="2"><title>${label}: $${c.toFixed(2)} per ticket</title></circle>` +
      `<text x="${n2(sx(t))}" y="${n2(ty)}" class="key mid" fill="${color}">${label}</text>` +
      `<text x="${n2(sx(t))}" y="${n2(ty + 15)}" class="note mid">$${c.toFixed(2)} a ticket</text>`
    );
  };

  const inner = `  <svg class="fig" viewBox="0 0 ${W} ${H}" role="img"
    aria-label="Cost per ticket against the confidence threshold. The curve is a bowl whose floor sits at 0.2, the value the cost arithmetic predicts. Choosing 0.5 out of habit sits well up the right wall.">
    <defs><clipPath id="cost-clip"><rect x="${M.left}" y="${M.top}" width="${PW}" height="${PH}" /></clipPath></defs>
    ${frame({ xLabel: 'confidence threshold you pick', yLabel: 'cost per ticket', yTicks: false })}
    ${yLabels}
    <g clip-path="url(#cost-clip)"><path class="series" d="${path(pts)}" stroke="${HONEST}" /></g>
    ${mark(derived, atDerived, HONEST, 'the arithmetic says 0.20', false)}
    ${mark(0.5, atHalf, HOT, 'the reflexive 0.50', true)}
  </svg>`;

  return component(
    inner,
    `Twenty thousand tickets: five dollars for a wrong approval, twenty for a wrong denial. The bowl's floor is the cheapest threshold to run, and it sits exactly where the arithmetic put it &mdash; 0.20, at $${atDerived.toFixed(2)} a ticket. Reaching for 0.5 out of habit costs $${atHalf.toFixed(2)}, ${Math.round((atHalf / atDerived - 1) * 100)}% more, on every ticket, forever. Past the right edge the curve climbs to $10: that is the cost of never approving anything.`,
  );
}

// --- write ------------------------------------------------------------------

const figures: [string, string][] = [
  ['Temperature.astro', figureTemperature()],
  ['Reliability.astro', await figureReliability()],
  ['Cost.astro', await figureCost()],
];

mkdirSync(OUT, { recursive: true });
for (const [name, source] of figures) {
  const file = resolve(OUT, name);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, source);
  console.log('wrote', file);
}
