import type { DomainKey } from './domains';
import type { EdgeType } from './edges';

export interface Node {
  id: string;
  name: string;
  domain: DomainKey;
  notes: string;
}

export interface Edge {
  source: string;
  target: string;
  type: EdgeType;
}

export const DEFAULT_NODES: Node[] = [
  { id: 'feynman', name: 'Feynman', domain: 'physics', notes: 'Path integrals, but the disposition not the framework' },
  { id: 'boltzmann', name: 'Boltzmann', domain: 'physics', notes: 'S = k ln Ω. Partition function as ur-framework' },
  { id: 'einstein', name: 'Einstein', domain: 'physics', notes: 'Equivalence principle as abduction' },
  { id: 'heisenberg', name: 'Heisenberg', domain: 'physics', notes: 'Uncertainty as fundamental' },
  { id: 'mandelbrot', name: 'Mandelbrot', domain: 'physics', notes: 'Scale invariance. Roughness resists smooth formalization' },
  { id: 'feigenbaum', name: 'Feigenbaum', domain: 'physics', notes: 'Universal constants of chaos' },
  { id: 'prigogine', name: 'Prigogine', domain: 'physics', notes: 'Dissipative structures. Order from irreversibility' },
  { id: 'vonneumann', name: 'von Neumann', domain: 'physics', notes: 'Formalized half the 20th century' },
  { id: 'oppenheimer', name: 'Oppenheimer', domain: 'physics', notes: 'Scientist as tragic political actor' },
  { id: 'shannon', name: 'Shannon', domain: 'physics', notes: 'Entropy as information. Channel capacity' },
  { id: 'godel', name: 'Gödel', domain: 'physics', notes: "Incompleteness. Systems can't prove truths about themselves" },
  { id: 'ulam', name: 'Ulam', domain: 'physics', notes: "Monte Carlo methods. Your research loop's paradigm" },
  { id: 'martin_ch', name: 'C.H. Martin', domain: 'physics', notes: 'Weightwatcher/HTSR. RG on transformer weights' },
  { id: 'jaynes_et', name: 'E.T. Jaynes', domain: 'physics', notes: 'MaxEnt. Probability as logic' },
  { id: 'davies', name: 'Paul Davies', domain: 'physics', notes: 'Mind of God. Math structure that appears designed' },
  { id: 'ashby', name: 'Ashby', domain: 'cybernetics', notes: 'Requisite Variety' },
  { id: 'beer', name: 'Stafford Beer', domain: 'cybernetics', notes: 'VSM. Variety as entropy' },
  { id: 'bateson', name: 'Bateson', domain: 'cybernetics', notes: 'Ecology of mind. Pattern that connects' },
  { id: 'wiener', name: 'Wiener', domain: 'cybernetics', notes: 'Feedback, control, communication' },
  { id: 'polanyi', name: 'Polanyi', domain: 'philosophy', notes: 'Tacit Dimension. We know more than we can tell' },
  { id: 'bostrom', name: 'Bostrom', domain: 'philosophy', notes: 'Framed x-risk. Superintelligence' },
  { id: 'metzinger', name: 'Metzinger', domain: 'philosophy', notes: 'Being No One. Phenomenal self' },
  { id: 'han', name: 'Byung-Chul Han', domain: 'philosophy', notes: 'Burnout Society' },
  { id: 'barad', name: 'Karen Barad', domain: 'philosophy', notes: 'Agential realism. Brilliant or unhinged' },
  { id: 'peirce', name: 'Peirce', domain: 'philosophy', notes: 'Abduction as inference' },
  { id: 'deutsch', name: 'David Deutsch', domain: 'philosophy', notes: 'Universal explainer. Explanation as physical' },
  { id: 'harris', name: 'Sam Harris', domain: 'philosophy', notes: 'Moral landscape. Topology outside physics' },
  { id: 'mcgowan', name: 'McGowan', domain: 'philosophy', notes: 'Hegel via Lacan. Contradiction as engine' },
  { id: 'engley', name: 'Engley', domain: 'philosophy', notes: 'Why Theory. AI as Big Other' },
  { id: 'hofstadter', name: 'Hofstadter', domain: 'philosophy', notes: 'GEB. Strange loops. Analogy as cognition' },
  { id: 'jaynes_j', name: 'Julian Jaynes', domain: 'philosophy', notes: 'Bicameral mind. Consciousness as cultural tech' },
  { id: 'huizinga', name: 'Huizinga', domain: 'philosophy', notes: 'Homo Ludens. Play underneath everything' },
  { id: 'chalmers', name: 'Chalmers', domain: 'philosophy', notes: 'Hard problem' },
  { id: 'dennett', name: 'Dennett', domain: 'philosophy', notes: 'Consciousness explained (away)' },
  { id: 'block', name: 'Ned Block', domain: 'philosophy', notes: 'Access vs phenomenal consciousness' },
  { id: 'nagel', name: 'Nagel', domain: 'philosophy', notes: 'What is it like to be a bat?' },
  { id: 'girard', name: 'Girard', domain: 'philosophy', notes: 'I See Satan Fall Like Lightning. Mimetic desire, scapegoat mechanism. The survival-of-Christianity argument is weaker than the mimetic theory it sits on' },
  { id: 'gibson', name: 'Gibson', domain: 'literature', notes: 'Invented the aesthetic we live inside' },
  { id: 'egan', name: 'Egan', domain: 'literature', notes: 'Hardest of the hard SF' },
  { id: 'chiang', name: 'Chiang', domain: 'literature', notes: 'Each story is a proof' },
  { id: 'lem', name: 'Lem', domain: 'literature', notes: 'Epistemology over engineering. Funnier' },
  { id: 'vinge', name: 'Vinge', domain: 'literature', notes: 'Ideas-first. Singularity concept' },
  { id: 'ksr', name: 'KSR', domain: 'literature', notes: 'Political ecology at scale' },
  { id: 'liu', name: 'Liu Cixin', domain: 'literature', notes: 'Three Body. Asimov for Chinese century' },
  { id: 'ferrante', name: 'Ferrante', domain: 'literature', notes: 'Neapolitan novels' },
  { id: 'knausgard', name: 'Knausgård', domain: 'literature', notes: 'Most honest or most performed honesty' },
  { id: 'vuong', name: 'Ocean Vuong', domain: 'literature', notes: 'Immigrant + queer bridge' },
  { id: 'borges', name: 'Borges', domain: 'literature', notes: 'Library of Babel. The séance room' },
  { id: 'cortazar', name: 'Cortázar', domain: 'literature', notes: 'Hopscotch. Non-linear invocation' },
  { id: 'dfw', name: 'DFW', domain: 'literature', notes: 'Recursive self-awareness. Irony exhaustion' },
  { id: 'hesse', name: 'Hesse', domain: 'literature', notes: 'Glass Bead Game = statement-space. But Knecht leaves' },
  { id: 'rand', name: 'Rand', domain: 'literature', notes: 'Wrong productively. Clarity as moral obligation' },
  { id: 'kundera', name: 'Kundera', domain: 'literature', notes: 'Novel as experiment. Kitsch as deepest basin' },
  { id: 'basile', name: 'J. Basile', domain: 'literature', notes: 'libraryofbabel.info. Literary conceit made computational' },
  { id: 'yurchak', name: 'Yurchak', domain: 'social_theory', notes: 'Hypernormalization. Basin decoupled from truth' },
  { id: 'menand', name: 'Menand', domain: 'social_theory', notes: "The Metaphysical Club. Pragmatism as a response to the Civil War's cost of certainty. Peirce, James, Holmes, Dewey as a single weather system" },
  { id: 'shlain', name: 'Shlain', domain: 'art', notes: 'Art & Physics. Same manifold, different projections' },
  { id: 'holzer', name: 'Jenny Holzer', domain: 'art', notes: 'Truisms. Text as projection' },
  { id: 'toussaint', name: 'Toussaint', domain: 'music', notes: 'NOLA R&B. QR code on Burgundy' },
  { id: 'bobby_charles', name: 'Bobby Charles', domain: 'music', notes: 'Swamp pop. Laid-back genius' },
  { id: 'zahavy', name: 'Zahavy', domain: 'ai_research', notes: "LLMs can't jump. Abduction needs embodiment" },
  { id: 'huntley', name: 'G. Huntley', domain: 'ai_research', notes: 'Ralph Wiggum Loop = Monte Carlo' },
  { id: 'chenglou', name: 'chenglou', domain: 'ai_research', notes: 'Pretext. Text as fluid' },
];

export const DEFAULT_EDGES: Edge[] = [
  { source: 'boltzmann', target: 'feynman', type: 'influenced' },
  { source: 'boltzmann', target: 'shannon', type: 'bridges' },
  { source: 'einstein', target: 'heisenberg', type: 'tension' },
  { source: 'einstein', target: 'feynman', type: 'influenced' },
  { source: 'feigenbaum', target: 'mandelbrot', type: 'co-domain' },
  { source: 'prigogine', target: 'boltzmann', type: 'extends' },
  { source: 'vonneumann', target: 'godel', type: 'co-domain' },
  { source: 'vonneumann', target: 'ulam', type: 'collaborated' },
  { source: 'godel', target: 'hofstadter', type: 'influenced' },
  { source: 'shannon', target: 'ashby', type: 'bridges' },
  { source: 'shannon', target: 'wiener', type: 'co-domain' },
  { source: 'jaynes_et', target: 'boltzmann', type: 'extends' },
  { source: 'martin_ch', target: 'boltzmann', type: 'applies' },
  { source: 'ashby', target: 'beer', type: 'influenced' },
  { source: 'wiener', target: 'ashby', type: 'influenced' },
  { source: 'wiener', target: 'bateson', type: 'influenced' },
  { source: 'bateson', target: 'beer', type: 'co-domain' },
  { source: 'peirce', target: 'polanyi', type: 'bridges' },
  { source: 'hofstadter', target: 'dfw', type: 'bridges' },
  { source: 'mcgowan', target: 'engley', type: 'collaborated' },
  { source: 'chalmers', target: 'dennett', type: 'tension' },
  { source: 'chalmers', target: 'nagel', type: 'co-domain' },
  { source: 'block', target: 'chalmers', type: 'co-domain' },
  { source: 'jaynes_j', target: 'dennett', type: 'tension' },
  { source: 'deutsch', target: 'polanyi', type: 'tension' },
  { source: 'huizinga', target: 'bateson', type: 'bridges' },
  { source: 'beer', target: 'boltzmann', type: 'bridges' },
  { source: 'polanyi', target: 'boltzmann', type: 'tension' },
  { source: 'hesse', target: 'boltzmann', type: 'bridges' },
  { source: 'kundera', target: 'harris', type: 'bridges' },
  { source: 'yurchak', target: 'beer', type: 'bridges' },
  { source: 'yurchak', target: 'feigenbaum', type: 'bridges' },
  { source: 'gibson', target: 'borges', type: 'bridges' },
  { source: 'borges', target: 'basile', type: 'influenced' },
  { source: 'cortazar', target: 'borges', type: 'co-domain' },
  { source: 'rand', target: 'peirce', type: 'tension' },
  { source: 'shlain', target: 'mandelbrot', type: 'bridges' },
  { source: 'davies', target: 'deutsch', type: 'co-domain' },
  { source: 'zahavy', target: 'peirce', type: 'applies' },
  { source: 'huntley', target: 'ulam', type: 'bridges' },
  { source: 'holzer', target: 'chenglou', type: 'bridges' },
  { source: 'mcgowan', target: 'rand', type: 'tension' },
  { source: 'prigogine', target: 'bateson', type: 'bridges' },
  { source: 'harris', target: 'shlain', type: 'bridges' },
  { source: 'dfw', target: 'kundera', type: 'bridges' },
  { source: 'lem', target: 'gibson', type: 'co-domain' },
  { source: 'lem', target: 'borges', type: 'bridges' },
  { source: 'feynman', target: 'deutsch', type: 'bridges' },
  { source: 'oppenheimer', target: 'vonneumann', type: 'co-domain' },
  { source: 'toussaint', target: 'bobby_charles', type: 'co-domain' },
  { source: 'girard', target: 'peirce', type: 'bridges' },
  { source: 'girard', target: 'harris', type: 'tension' },
  { source: 'girard', target: 'mcgowan', type: 'co-domain' },
  { source: 'menand', target: 'peirce', type: 'bridges' },
  { source: 'menand', target: 'yurchak', type: 'co-domain' },
];
