import { useEffect, useRef, useState } from 'react';
import {
  apply,
  triadName,
  triadPcs,
  type PLR,
  type Triad,
} from '@/lib/music/neoRiemannian';
import Z12Clock from './Z12Clock';

// Behold for Module 7. The hexatonic cycle generated by alternating P
// and L on a major triad: C → c → A♭ → a♭ → E → e → C. Six steps
// return home. Animates one step per beat so the listener sees the
// triad rotate, the shared notes anchor, and the moving voice slide.

const SEED: Triad = { root: 0, quality: 'major' }; // C major

interface Step {
  triad: Triad;
  op: PLR | null; // op that produced this triad (null for the seed)
}

function buildCycle(): Step[] {
  const ops: PLR[] = ['P', 'L', 'P', 'L', 'P', 'L'];
  const steps: Step[] = [{ triad: SEED, op: null }];
  let t = SEED;
  for (const op of ops) {
    t = apply(t, op);
    steps.push({ triad: t, op });
  }
  return steps;
}

const CYCLE = buildCycle();
const STAGE_MS = 1500;

export default function Module7Behold() {
  const wrapRef = useRef<HTMLDivElement>(null);
  const [i, setI] = useState(0);
  const [running, setRunning] = useState(false);
  const timerRef = useRef<number | null>(null);

  useEffect(() => {
    if (!running) return;
    timerRef.current = window.setInterval(() => {
      setI((x) => (x + 1) % CYCLE.length);
    }, STAGE_MS);
    return () => {
      if (timerRef.current != null) {
        window.clearInterval(timerRef.current);
        timerRef.current = null;
      }
    };
  }, [running]);

  useEffect(() => {
    const el = wrapRef.current;
    if (!el) return;
    if (typeof IntersectionObserver === 'undefined') {
      setRunning(true);
      return;
    }
    const obs = new IntersectionObserver(
      (entries) => {
        for (const e of entries) {
          if (e.intersectionRatio > 0.3) {
            setRunning(true);
            obs.disconnect();
            return;
          }
        }
      },
      { threshold: [0.3] },
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, []);

  const step = CYCLE[i];
  const pcs = triadPcs(step.triad);
  const sorted = [...pcs].sort((a, b) => a - b);
  const polygon = [...sorted, sorted[0]];

  return (
    <div ref={wrapRef} className="m7-behold">
      <Z12Clock
        pcs={sorted}
        polygonPath={polygon}
        tonicPc={step.triad.root}
        labels="both"
        size={240}
        ariaLabel={`${triadName(step.triad)} triad`}
      />
      <div className="m7-behold-label">
        <span className="m7-behold-name">{triadName(step.triad)}</span>
        {step.op && (
          <span className="m7-behold-op">via {step.op}</span>
        )}
      </div>
      <p className="m7-behold-caption">
        Alternating <strong>P</strong> and <strong>L</strong> from C
        major walks a six-step hexatonic cycle: <em>C → Cm → A♭ → A♭m
        → E → Em → C</em>. Each step moves exactly one voice by a half
        step; the other two pitches sit still.
      </p>
    </div>
  );
}
